# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('RG', models.BigIntegerField(max_length=10)),
                ('CPF', models.BigIntegerField(max_length=11)),
                ('RA', models.BigIntegerField(max_length=20)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
