# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Associados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='Data_de_Associacao',
        ),
        migrations.RemoveField(
            model_name='post',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='post',
            name='RA',
        ),
        migrations.RemoveField(
            model_name='post',
            name='RG',
        ),
    ]
