# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associados', '0002_auto_20160707_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CPF',
            field=models.BigIntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='RA',
            field=models.BigIntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='RG',
            field=models.BigIntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
